### PR TITLE
corrected datagov100.json to data.json in two places

### PR DESCRIPTION
**Pull request by daniellecrobinson**

### CODE REVIEW

**Comment by zeke** [comment]
There's a `curl` invocation earlier in the readme that saves the file as `data.json`:

```
curl https://raw.githubusercontent.com/jsonlines/guide/master/datagov100.json > data.json
```

**Comment by daniellecrobinson** [comment]
Yes, I saw that as I worked through the guide -  in some of the other examples further down in the guide are datagov100.json rather than data.json:

$ cat datagov100.json | jsonmap "if (this.maintainer) this.maintainer = this.maintainer.toUpperCase()"

So, I was trying to change it in those spots.

**Comment by zeke** [comment]
Ahh, got red and green confused. In that case, 👍

**Comment by max-mapper** [comment]
Thanks @daniellecrobinson, excellent PR!

**Pull request merged**
